apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistics-app-deployment
  labels:
    app: logistics
spec:
  replicas: 2 # Enterprise High Availability: Run 2 copies of the app!
  selector:
    matchLabels:
      app: logistics
  template:
    metadata:
      labels:
        app: logistics
    spec:
      containers:
      - name: logistics-container
        image: parth1717/logistics-app:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        
        # Enterprise Best Practice: Self-Healing Probes
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10



# notes to self :
# kubectl get pods
# kubectl get services
# kubectl get deployments
# kubectl apply -f k8s/
# for aws : ssh -i aws-key.pem ubuntu@13.234.110.174 in the command prompt in the vs code folder window

# sudo systemctl status k3s
# sudo systemctl restart k3s
# sudo k3s kubectl get pods

# for refreshing ram : 
# sudo fallocate -l 1G /swapfile
# sudo chmod 600 /swapfile
# sudo mkswap /swapfile
# sudo swapon /swapfile