apiVersion: v1
kind: Service
metadata:
  name: logistics-app-service
spec:
  type: LoadBalancer # Exposes the app outside the cluster
  selector:
    app: logistics
  ports:
    - protocol: TCP
      port: 8000       # The port we access from our browser
      targetPort: 8000 # The port the container is listening on